--PRD_ID, PRD_NAME, CATEGORY, PRICE, STOCK
CREATE TABLE TB_PRODUCT(
	PRD_ID VARCHAR2(15) CONSTRAINT PK_PRD PRIMARY KEY,
	PRD_NAME NVARCHAR2(30) CONSTRAINT NAME_NOT_NULL NOT NULL,
	CATEGORY VARCHAR(30),
	PRICE NUMBER ,
	STOCK NUMBER
);
