-- 주문정보 ORDER
-- 주문고유ID 주문회원ID 주문상품ID 주문수량 주문날짜
-- ORDER_ID, USER_ID, PRODUCT_ID ORDER_NO, ORDER_DATE

CREATE TABLE TB_ORDER (
	ORDER_ID VARCHAR2(15) NOT NULL,
	USER_ID VARCHAR2(20) UNIQUE NOT NULL,
	PRODUCT_ID VARCHAR2(15) NOT NULL,
	ORDER_NO NUMBER NOT NULL,
	ORDER_DATE DATE NOT NULL
);
	
