--PRD_ID, PRD_NAME, CATEGORY, PRICE, STOCK
CREATE TABLE TB_PRODUCT(
	PRD_ID VARCHAR2(15) CONSTRAINT PK_PRD PRIMARY KEY,
	PRD_NAME NVARCHAR2(30) NOT NULL,
	CATEGORY VARCHAR(30),
	PRICE NUMBER ,
	STOCK NUMBER
);

-- 주문정보 ORDER
-- 주문고유ID 주문회원ID 주문상품ID 주문수량 주문날짜
-- ORDER_ID, USER_ID, PRODUCT_ID ORDER_NO, ORDER_DATE

CREATE TABLE TB_ORDER (
	ORDER_ID VARCHAR2(15) NOT NULL,
	USER_ID VARCHAR2(20) UNIQUE NOT NULL,
	PRODUCT_ID VARCHAR2(15) NOT NULL,
	ORDER_NO NUMBER NOT NULL,
	ORDER_DATE DATE NOT NULL
);
	
CREATE TABLE TB_CUSTOMER (
	USER_ID VARCHAR2(20) NOT NULL UNIQUE,
	USER_PWD VARCHAR2(20) NOT NULL,
	USER_NAME VARCHAR2(30) NOT NULL,
	PHONE VARCHAR2(15) NOT NULL,
	ADDRESS VARCHAR2(200)
);

SELECT * FROM TB_PRODUCT
SELECT * FROM TB_ORDER
SELECT * FROM TB_CUSTOMER
